global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'database_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['database:8050']
        labels:
          application: 'Database Service'
  - job_name: 'profile_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'profile:8080' ]
        labels:
          application: 'Profile Service'
  - job_name: 'friendship_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'friendship:8082' ]
        labels:
          application: 'Friendship Service'
  - job_name: 'gateway_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8030']
        labels:
          application: 'Gateway Service'
  - job_name: 'communication_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['communication:8081']
        labels:
          application: 'Communication Service'