FROM openjdk:21

ARG JAR_FILE=microservices/gateway/target/gateway-1.0-SNAPSHOT.jar
ARG APP_FILE=application-docker.yaml
COPY ${JAR_FILE} gateway.jar
COPY ${APP_FILE} application.yaml
EXPOSE 8030
ENTRYPOINT ["java","-jar","/gateway.jar"]