version: '3.7'

services:
  gateway:
    image: skillbox43/social-net-backend:gateway
    container_name: "gateway"
    networks:
      - social-net
    ports:
      - "8030:8030"

  communication:
    image: skillbox43/social-net-backend:communication
    container_name: "communication"
    networks:
      - social-net

  database:
    image: skillbox43/social-net-backend:database
    container_name: "database"
    networks:
      - social-net

  friendship:
    image: skillbox43/social-net-backend:friendship
    container_name: "friendship"
    networks:
      - social-net

  profile:
    image: skillbox43/social-net-backend:profile
    container_name: "profile"
    networks:
      - social-net

  grafana:
    build: '/home/socialnet/metrics/grafana'
    container_name: "grafana"
    ports:
      - "3000:3000"
    volumes:
      - /home/socialnet/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - social-net

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - /home/socialnet/metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/socialnet/prometheus:/prometheus
    networks:
      - social-net

networks:
  social-net:
    driver: bridge