server:
  port: 8030

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

max-image-size: 1048576

app:
  jwt:
    accessTokenLifeTime: 2h
    refreshTokenLifeTime: 2h
    authScheme: Bearer
  security:
    passwordStrength: 12

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true